//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickItem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickItem.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this group.
        /// </summary>
        internal static string ContextMenu_Group_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Group_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit groups....
        /// </summary>
        internal static string ContextMenu_Group_EditGroups {
            get {
                return ResourceManager.GetString("ContextMenu_Group_EditGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item.
        /// </summary>
        internal static string ContextMenu_Item_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Item_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this item....
        /// </summary>
        internal static string ContextMenu_Item_EditItem {
            get {
                return ResourceManager.GetString("ContextMenu_Item_EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit layouts....
        /// </summary>
        internal static string ContextMenu_Layout_EditLayouts {
            get {
                return ResourceManager.GetString("ContextMenu_Layout_EditLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Item.
        /// </summary>
        internal static string ItemContextMenu_SetItem {
            get {
                return ResourceManager.GetString("ItemContextMenu_SetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the active layout. .
        /// </summary>
        internal static string Settings_ActiveLayout_Description {
            get {
                return ResourceManager.GetString("Settings_ActiveLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Layout.
        /// </summary>
        internal static string Settings_ActiveLayout_Name {
            get {
                return ResourceManager.GetString("Settings_ActiveLayout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for when an item is considered found when searching. Smaller values will have fewer false positives, but may reject valid items. Larger values will be more tolerant, but may introduce false positives.
        ///Min: 0.05
        ///Default: 0.1
        ///Max: 0.5.
        /// </summary>
        internal static string Settings_SearchAcceptThreshold_Description {
            get {
                return ResourceManager.GetString("Settings_SearchAcceptThreshold_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search threshold.
        /// </summary>
        internal static string Settings_SearchAcceptThreshold_Name {
            get {
                return ResourceManager.GetString("Settings_SearchAcceptThreshold_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale down the image when searching to improve search performance. Smaller values may make the search inaccurate (fail to find the item or finds the wrong item). Larger values will make the search slower.
        ///Min: 0.5
        ///Default: 0.6
        ///Max: 1.0.
        /// </summary>
        internal static string Settings_SearchImageScale_Description {
            get {
                return ResourceManager.GetString("Settings_SearchImageScale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search image scale.
        /// </summary>
        internal static string Settings_SearchImageScale_Name {
            get {
                return ResourceManager.GetString("Settings_SearchImageScale_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey to toggle visibility of all items.
        /// </summary>
        internal static string Settings_VisibilityHotkey_Description {
            get {
                return ResourceManager.GetString("Settings_VisibilityHotkey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Toggle.
        /// </summary>
        internal static string Settings_VisibilityHotkey_Name {
            get {
                return ResourceManager.GetString("Settings_VisibilityHotkey_Name", resourceCulture);
            }
        }
    }
}
