name: Full Build

on:
  workflow_call:
    outputs:
      module_version:
        description: "Module version"
        value: ${{ jobs.build.outputs.module_version }}
      build_version:
        description: "Module + build version"
        value: ${{ jobs.build.outputs.build_version }}

jobs:
  build:
    runs-on: windows-latest

    outputs:
      module_version: ${{ steps.version.outputs.module_version }}
      build_version: ${{ steps.version.outputs.build_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore
        shell: powershell
        run: |
          cd ItemFinder
          . ".\BuildExternals.ps1"
          BuildOpenCvForWindows "x64" $TRUE

      - name: Restore
        shell: powershell
        run: |
          msbuild QuickItem.sln /t:Restore /p:RestorePackagesConfig=true /p:configuration=Release

      - name: Build
        shell: powershell
        run: |
          msbuild QuickItem.sln /t:build /p:configuration=Release -maxcpucount

      - name: Set Version Variable
        id: version
        shell: powershell
        run: |
          $json = Get-Content .\QuickItem\manifest.json -Raw | ConvertFrom-Json
          $modulever = "$($json.version)"
          $buildver = "$($json.version)-${{ github.run_number }}"
          echo "::set-output name=module_version::${modulever}"
          echo "::set-output name=build_version::${buildver}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: quickitem_${{steps.version.outputs.build_version}}
          path: QuickItem/bin/Release
