name: CI Build

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
      - main
      - feature/ci

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
